### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by BijoySingh** [DheerendraRathor/ldap-oauth2#4]
The widget should allow passing a parameter for changing the color of the button.
This is essential as it allows the various bodies to customize the buttons to match their interfaces.
Additional could be allow passing an entire CSS file

**Comment by DheerendraRathor** [comment]
Adding an entire CSS file will lead to various complications like CORS. Also that might enable some vulnerablities. Currently I've added support for 3 colors viz div background color, foreground color and logout link color.
